[tool.black]
line-length = 100
target-version = ['py38']
include = '''(^/YYY/|^/tests/|^/setup).*\.py$'''
extend-exclude = '''
(
  ^/scrap/*         # exclude scrap files
  | .*scrap\..*     # exclude scrap files
  | .*scrap_\..*    # exclude scrap files
  | ^/docs/*        # exclude docs files
)
'''
